// Testi aggiunti all'app rispetto al design. [it, en, fr, es, pl, ro]
export default {
  yourName: ['Il tuo nome', 'Your name', 'Votre prénom', 'Tu nombre', 'Twoje imię', 'Numele tău'],
  groupNameLabel: ['Nome del gruppo', 'Group name', 'Nom du groupe', 'Nombre del grupo', 'Nazwa grupy', 'Numele grupului'],
  groupNamePh: ['Es. Parrocchia San Luca', "E.g. St Luke's Parish", 'Ex. Paroisse Saint-Luc', 'Ej. Parroquia San Lucas', 'Np. Parafia św. Łukasza', 'Ex. Parohia Sf. Luca'],
  groupCreateHint: ['Riceverai un codice da dare ai membri.', "You'll get a code to give your members.", 'Vous recevrez un code à donner aux membres.', 'Recibirás un código para tus miembros.', 'Otrzymasz kod dla uczestników.', 'Vei primi un cod pentru membri.'],
  codeChecking: ['Verifico il codice…', 'Checking code…', 'Vérification du code…', 'Comprobando el código…', 'Sprawdzam kod…', 'Verific codul…'],
  codeNotFound: ['Codice non trovato', 'Code not found', 'Code introuvable', 'Código no encontrado', 'Nie znaleziono kodu', 'Cod negăsit'],
  codeFound: ['✓ {group} · capogruppo {leader}', '✓ {group} · leader {leader}', '✓ {group} · accompagnateur {leader}', '✓ {group} · responsable {leader}', '✓ {group} · lider {leader}', '✓ {group} · lider {leader}'],
  needsOnline: ['Serve internet per entrare nel gruppo.', 'You need internet to join the group.', 'Internet est nécessaire pour rejoindre le groupe.', 'Necesitas internet para unirte al grupo.', 'Aby dołączyć do grupy, potrzebny jest internet.', 'Ai nevoie de internet ca să intri în grup.'],
  localMode: ['Modalità locale: i dati restano su questo telefono, il gruppo condiviso non è attivo.', 'Local mode: data stays on this phone, shared groups are off.', 'Mode local : les données restent sur ce téléphone, groupe partagé désactivé.', 'Modo local: los datos quedan en este teléfono, el grupo compartido no está activo.', 'Tryb lokalny: dane zostają na tym telefonie, wspólna grupa nieaktywna.', 'Mod local: datele rămân pe acest telefon, grupul comun nu e activ.'],
  errGeneric: ['Qualcosa è andato storto. Riprova.', 'Something went wrong. Try again.', "Un problème est survenu. Réessayez.", 'Algo salió mal. Inténtalo de nuevo.', 'Coś poszło nie tak. Spróbuj ponownie.', 'Ceva n-a mers. Încearcă din nou.'],
  scanCamera: ['Apri fotocamera', 'Open camera', "Ouvrir l'appareil photo", 'Abrir cámara', 'Otwórz aparat', 'Deschide camera'],
  capture: ['Scatta e leggi', 'Capture and read', 'Prendre et lire', 'Capturar y leer', 'Zrób zdjęcie i odczytaj', 'Fotografiază și citește'],
  scanPhoto: ['Scegli una foto', 'Choose a photo', 'Choisir une photo', 'Elegir una foto', 'Wybierz zdjęcie', 'Alege o fotografie'],
  scanManual: ['Inserisci la MRZ a mano', 'Type the MRZ by hand', 'Saisir la MRZ à la main', 'Escribir la MRZ a mano', 'Wpisz MRZ ręcznie', 'Introdu MRZ manual'],
  mrzHelp: ['Le 2 righe con i simboli < in fondo alla pagina con la foto.', 'The 2 lines with < symbols at the bottom of the photo page.', 'Les 2 lignes avec des < en bas de la page photo.', 'Las 2 líneas con símbolos < al pie de la página de la foto.', 'Dwie linie ze znakami < na dole strony ze zdjęciem.', 'Cele 2 rânduri cu simboluri < din josul paginii cu fotografia.'],
  readMrz: ['Leggi', 'Read', 'Lire', 'Leer', 'Odczytaj', 'Citește'],
  scanFail: ['Non riesco a leggere la MRZ. Avvicinati, evita i riflessi o inseriscila a mano.', "Couldn't read the MRZ. Move closer, avoid glare, or type it in.", 'Impossible de lire la MRZ. Approchez-vous, évitez les reflets ou saisissez-la.', 'No puedo leer la MRZ. Acércate, evita reflejos o escríbela a mano.', 'Nie mogę odczytać MRZ. Podejdź bliżej, unikaj odblasków lub wpisz ręcznie.', 'Nu pot citi MRZ. Apropie-te, evită reflexiile sau introdu-o manual.'],
  scanChecksBad: ['Alcune cifre di controllo non tornano: verifica i dati prima di salvare.', "Some check digits don't match: check the data before saving.", 'Certains chiffres de contrôle ne correspondent pas : vérifiez avant d’enregistrer.', 'Algunos dígitos de control no coinciden: revisa los datos antes de guardar.', 'Niektóre cyfry kontrolne się nie zgadzają: sprawdź dane przed zapisem.', 'Unele cifre de control nu corespund: verifică datele înainte de salvare.'],
  camDenied: ['Fotocamera non disponibile: scegli una foto.', 'Camera unavailable: choose a photo.', 'Appareil photo indisponible : choisissez une photo.', 'Cámara no disponible: elige una foto.', 'Aparat niedostępny: wybierz zdjęcie.', 'Camera indisponibilă: alege o fotografie.'],
  ocrLoading: ['Preparo il lettore (solo la prima volta)…', 'Preparing the reader (first time only)…', 'Préparation du lecteur (la première fois)…', 'Preparando el lector (solo la primera vez)…', 'Przygotowuję czytnik (tylko za pierwszym razem)…', 'Pregătesc cititorul (doar prima dată)…'],
  confirmData: ['Controlla i dati', 'Check the details', 'Vérifiez les données', 'Revisa los datos', 'Sprawdź dane', 'Verifică datele'],
  fSurname: ['Cognome', 'Surname', 'Nom', 'Apellidos', 'Nazwisko', 'Nume'],
  fGiven: ['Nomi', 'Given names', 'Prénoms', 'Nombre', 'Imiona', 'Prenume'],
  fBirth: ['Nascita', 'Date of birth', 'Naissance', 'Nacimiento', 'Data urodzenia', 'Data nașterii'],
  pinCreate: ['Crea il PIN della cassaforte', 'Create your vault PIN', 'Créez le code du coffre', 'Crea el PIN de la caja fuerte', 'Utwórz PIN sejfu', 'Creează PIN-ul seifului'],
  pinCreateD: ['Almeno 6 cifre. Serve per aprire i documenti, anche offline. Nessuno può recuperarlo: non dimenticarlo.', "At least 6 digits. It opens your documents, even offline. Nobody can recover it: don't forget it.", "Au moins 6 chiffres. Il ouvre vos documents, même hors ligne. Personne ne peut le récupérer : ne l'oubliez pas.", 'Al menos 6 cifras. Abre tus documentos, incluso sin conexión. Nadie puede recuperarlo: no lo olvides.', 'Co najmniej 6 cyfr. Otwiera dokumenty, także offline. Nikt go nie odzyska: nie zapomnij.', 'Minim 6 cifre. Deschide documentele, chiar și offline. Nimeni nu-l poate recupera: nu-l uita.'],
  pin: ['PIN', 'PIN', 'Code', 'PIN', 'PIN', 'PIN'],
  pinRepeat: ['Ripeti il PIN', 'Repeat PIN', 'Répétez le code', 'Repite el PIN', 'Powtórz PIN', 'Repetă PIN-ul'],
  pinMismatch: ['I PIN non coincidono', "PINs don't match", 'Les codes ne correspondent pas', 'Los PIN no coinciden', 'PIN-y się różnią', 'PIN-urile nu coincid'],
  pinShort: ['Il PIN deve avere almeno 6 cifre', 'PIN must be at least 6 digits', 'Le code doit avoir au moins 6 chiffres', 'El PIN debe tener al menos 6 cifras', 'PIN musi mieć co najmniej 6 cyfr', 'PIN-ul trebuie să aibă minim 6 cifre'],
  pinWrong: ['PIN errato', 'Wrong PIN', 'Code incorrect', 'PIN incorrecto', 'Błędny PIN', 'PIN greșit'],
  unlockPin: ['Sblocca con il PIN', 'Unlock with PIN', 'Déverrouiller avec le code', 'Desbloquear con PIN', 'Odblokuj PIN-em', 'Deblochează cu PIN'],
  lockNow: ['Blocca', 'Lock', 'Verrouiller', 'Bloquear', 'Zablokuj', 'Blochează'],
  save: ['Salva', 'Save', 'Enregistrer', 'Guardar', 'Zapisz', 'Salvează'],
  cancelBtn: ['Annulla', 'Cancel', 'Annuler', 'Cancelar', 'Anuluj', 'Anulează'],
  docEmpty: ['Ancora nessun documento.', 'No documents yet.', 'Aucun document pour l’instant.', 'Aún no hay documentos.', 'Brak dokumentów.', 'Încă niciun document.'],
  addDocTitle: ['Nuovo documento', 'New document', 'Nouveau document', 'Nuevo documento', 'Nowy dokument', 'Document nou'],
  kPassport: ['Passaporto', 'Passport', 'Passeport', 'Pasaporte', 'Paszport', 'Pașaport'],
  kId: ["Carta d'identità", 'ID card', "Carte d'identité", 'DNI', 'Dowód osobisty', 'Carte de identitate'],
  kBoarding: ["Carta d'imbarco", 'Boarding pass', "Carte d'embarquement", 'Tarjeta de embarque', 'Karta pokładowa', 'Card de îmbarcare'],
  kHotel: ['Voucher hotel', 'Hotel voucher', "Bon d'hôtel", 'Bono de hotel', 'Voucher hotelowy', 'Voucher hotel'],
  kInsurance: ['Assicurazione', 'Insurance', 'Assurance', 'Seguro', 'Ubezpieczenie', 'Asigurare'],
  kTicket: ['Biglietto', 'Ticket', 'Billet', 'Billete', 'Bilet', 'Bilet'],
  kOther: ['Altro', 'Other', 'Autre', 'Otro', 'Inne', 'Altele'],
  docType: ['Tipo', 'Type', 'Type', 'Tipo', 'Rodzaj', 'Tip'],
  docTitle: ['Titolo', 'Title', 'Titre', 'Título', 'Tytuł', 'Titlu'],
  docNote: ['Dettagli', 'Details', 'Détails', 'Detalles', 'Szczegóły', 'Detalii'],
  docFile: ['Foto o PDF', 'Photo or PDF', 'Photo ou PDF', 'Foto o PDF', 'Zdjęcie lub PDF', 'Foto sau PDF'],
  docCode: ['Codice del biglietto (per il QR)', 'Ticket code (for the QR)', 'Code du billet (pour le QR)', 'Código del billete (para el QR)', 'Kod biletu (do QR)', 'Codul biletului (pentru QR)'],
  openFile: ['Apri file', 'Open file', 'Ouvrir le fichier', 'Abrir archivo', 'Otwórz plik', 'Deschide fișierul'],
  deleteBtn: ['Elimina', 'Delete', 'Supprimer', 'Eliminar', 'Usuń', 'Șterge'],
  confirmDelete: ['Eliminare questo documento?', 'Delete this document?', 'Supprimer ce document ?', '¿Eliminar este documento?', 'Usunąć ten dokument?', 'Ștergi acest document?'],
  cloudCopy: ['Copia cifrata anche nel cloud', 'Encrypted copy also in the cloud', 'Copie chiffrée aussi dans le cloud', 'Copia cifrada también en la nube', 'Zaszyfrowana kopia także w chmurze', 'Copie criptată și în cloud'],
  lost1Dx: ['Polizia o Carabinieri. Porta questa copia.', 'Police or Carabinieri. Bring this copy.', 'Police ou Carabiniers. Apportez cette copie.', 'Policía o Carabinieri. Lleva esta copia.', 'Policja lub Karabinierzy. Weź tę kopię.', 'Poliție sau Carabinieri. Ia această copie.'],
  lost2Dx: ["Per il passaporto d'emergenza servono la denuncia e una foto.", 'An emergency passport needs the report and a photo.', "Le passeport d'urgence nécessite la déclaration et une photo.", 'El pasaporte de emergencia requiere la denuncia y una foto.', 'Paszport tymczasowy wymaga zgłoszenia i zdjęcia.', 'Pașaportul de urgență cere plângerea și o fotografie.'],
  nearest: ['Il più vicino', 'Nearest', 'Le plus proche', 'El más cercano', 'Najbliższy', 'Cel mai apropiat'],
  searching: ['Cerco…', 'Searching…', 'Recherche…', 'Buscando…', 'Szukam…', 'Caut…'],
  greetMorning: ['Buongiorno', 'Good morning', 'Bonjour', 'Buenos días', 'Dzień dobry', 'Bună dimineața'],
  greetAfternoon: ['Buon pomeriggio', 'Good afternoon', 'Bon après-midi', 'Buenas tardes', 'Dzień dobry', 'Bună ziua'],
  greetEvening: ['Buonasera', 'Good evening', 'Bonsoir', 'Buenas noches', 'Dobry wieczór', 'Bună seara'],
  rome: ['Roma', 'Rome', 'Rome', 'Roma', 'Rzym', 'Roma'],
  calm: ['Zona tranquilla', 'Calm area', 'Zone calme', 'Zona tranquila', 'Spokojna okolica', 'Zonă liniștită'],
  calmD: ['Nessun avviso intorno a te', 'No alerts around you', 'Aucune alerte autour de vous', 'Ningún aviso a tu alrededor', 'Brak ostrzeżeń w pobliżu', 'Niciun avertisment în jur'],
  withGroup: ['Sei con il gruppo', "You're with the group", 'Vous êtes avec le groupe', 'Estás con el grupo', 'Jesteś z grupą', 'Ești cu grupul'],
  withGroupD: ['La guida è a {d}', 'Your guide is {d} away', 'Le guide est à {d}', 'El guía está a {d}', 'Przewodnik jest {d} od ciebie', 'Ghidul e la {d}'],
  outZone: ['Fuori dalla zona del gruppo', 'Outside the group zone', 'Hors de la zone du groupe', 'Fuera de la zona del grupo', 'Poza strefą grupy', 'În afara zonei grupului'],
  outZoneD: ['Il gruppo è a {d} · tocca per la strada', 'Group is {d} away · tap for directions', 'Le groupe est à {d} · touchez pour l’itinéraire', 'El grupo está a {d} · toca para la ruta', 'Grupa jest {d} stąd · dotknij, by wyznaczyć trasę', 'Grupul e la {d} · atinge pentru traseu'],
  leaderStat: ['{n} di {m} nella zona', '{n} of {m} in the zone', '{n} sur {m} dans la zone', '{n} de {m} en la zona', '{n} z {m} w strefie', '{n} din {m} în zonă'],
  leaderStatD: ['{name} è a {d} dal gruppo', '{name} is {d} from the group', '{name} est à {d} du groupe', '{name} está a {d} del grupo', '{name} jest {d} od grupy', '{name} e la {d} de grup'],
  leaderAllIn: ['Nessuno è fuori zona', 'Nobody is outside the zone', 'Personne hors de la zone', 'Nadie fuera de la zona', 'Nikt poza strefą', 'Nimeni în afara zonei'],
  noGps: ['Posizione non disponibile', 'Location unavailable', 'Position indisponible', 'Ubicación no disponible', 'Lokalizacja niedostępna', 'Locație indisponibilă'],
  noGpsD: ['Attiva la localizzazione per gli avvisi di sicurezza.', 'Turn on location for safety alerts.', 'Activez la localisation pour les alertes.', 'Activa la ubicación para los avisos de seguridad.', 'Włącz lokalizację, by dostawać ostrzeżenia.', 'Activează locația pentru avertismente.'],
  noPlanYet: ['Il capogruppo non ha ancora pubblicato il programma di oggi.', "Your leader hasn't published today's plan yet.", "L'accompagnateur n'a pas encore publié le programme du jour.", 'El responsable aún no ha publicado el plan de hoy.', 'Lider nie opublikował jeszcze planu na dziś.', 'Liderul nu a publicat încă programul de azi.'],
  planByLeader: ['Programma di {name}, capogruppo · {tour}', 'Plan by {name}, group leader · {tour}', 'Programme de {name}, accompagnateur · {tour}', 'Plan de {name}, responsable · {tour}', 'Plan lidera {name} · {tour}', 'Programul liderului {name} · {tour}'],
  yourPlan: ['Il tuo programma · {tour}', 'Your plan · {tour}', 'Votre programme · {tour}', 'Tu plan · {tour}', 'Twój plan · {tour}', 'Programul tău · {tour}'],
  customPlan: ['Personalizzato', 'Custom', 'Personnalisé', 'Personalizado', 'Własny', 'Personalizat'],
  fromPlace: ['Partenza da {place}', 'Departure from {place}', 'Départ de {place}', 'Salida desde {place}', 'Start: {place}', 'Plecare de la {place}'],
  leaderMsg: ['Messaggio del capogruppo', 'Message from your leader', "Message de l'accompagnateur", 'Mensaje del responsable', 'Wiadomość od lidera', 'Mesaj de la lider'],
  settings: ['Impostazioni', 'Settings', 'Réglages', 'Ajustes', 'Ustawienia', 'Setări'],
  locating: ['Cerco la tua posizione…', 'Finding your location…', 'Recherche de votre position…', 'Buscando tu ubicación…', 'Szukam twojej lokalizacji…', 'Caut locația ta…'],
  locOff: ['Posizione non disponibile: attiva la localizzazione.', 'Location unavailable: turn on location.', 'Position indisponible : activez la localisation.', 'Ubicación no disponible: activa la ubicación.', 'Lokalizacja niedostępna: włącz ją.', 'Locație indisponibilă: activeaz-o.'],
  meetingPoint: ["Punto d'incontro", 'Meeting point', 'Point de rendez-vous', 'Punto de encuentro', 'Miejsce zbiórki', 'Punct de întâlnire'],
  directions: ['Indicazioni', 'Directions', 'Itinéraire', 'Cómo llegar', 'Trasa', 'Indicații'],
  guide: ['Guida', 'Guide', 'Guide', 'Guía', 'Przewodnik', 'Ghid'],
  you: ['Tu', 'You', 'Vous', 'Tú', 'Ty', 'Tu'],
  opensAt: ['Apre alle {t}', 'Opens at {t}', 'Ouvre à {t}', 'Abre a las {t}', 'Otwarcie o {t}', 'Se deschide la {t}'],
  closedToday: ['Chiuso oggi', 'Closed today', "Fermé aujourd'hui", 'Cerrado hoy', 'Dziś zamknięte', 'Închis azi'],
  alwaysOpen: ['Sempre accessibile', 'Always open', 'Toujours accessible', 'Siempre abierto', 'Zawsze otwarte', 'Mereu deschis'],
  freeToday: ['Oggi è gratis: prima domenica del mese', "Free today: it's the first Sunday of the month", "Gratuit aujourd'hui : premier dimanche du mois", 'Hoy es gratis: primer domingo del mes', 'Dziś za darmo: pierwsza niedziela miesiąca', 'Azi e gratis: prima duminică a lunii'],
  nextFree: ['Gratis la prima domenica del mese · prossima: {date}', 'Free on the first Sunday of the month · next: {date}', 'Gratuit le premier dimanche du mois · prochain : {date}', 'Gratis el primer domingo del mes · próximo: {date}', 'Za darmo w pierwszą niedzielę miesiąca · najbliższa: {date}', 'Gratis în prima duminică a lunii · următoarea: {date}'],
  freeResidents: ['Prima domenica gratis solo per i residenti a Roma', 'First Sunday free for Rome residents only', 'Premier dimanche gratuit seulement pour les résidents', 'Primer domingo gratis solo para residentes en Roma', 'Pierwsza niedziela gratis tylko dla mieszkańców Rzymu', 'Prima duminică gratis doar pentru rezidenții Romei'],
  officialSite: ['Sito ufficiale', 'Official site', 'Site officiel', 'Web oficial', 'Oficjalna strona', 'Site oficial'],
  alreadyInPlan: ['Già nel programma', 'Already in your plan', 'Déjà au programme', 'Ya está en el plan', 'Już w planie', 'Deja în program'],
  onlyLeader: ['Il programma lo decide il capogruppo', 'Your group leader sets the plan', "C'est l'accompagnateur qui fixe le programme", 'El plan lo decide el responsable', 'Plan ustala lider grupy', 'Programul îl stabilește liderul'],
  buyOfficial: ['Compra sul sito ufficiale', 'Buy on the official site', 'Acheter sur le site officiel', 'Comprar en la web oficial', 'Kup na oficjalnej stronie', 'Cumpără de pe site-ul oficial'],
  saveTicket: ['Ho comprato: salva il biglietto', 'Bought it: save the ticket', "C'est acheté : enregistrer le billet", 'Ya lo compré: guardar el billete', 'Kupiony: zapisz bilet', 'L-am cumpărat: salvează biletul'],
  ticketHow: ['Compra sul sito ufficiale, poi salva qui il codice o il PDF: lo ritrovi in Documenti, anche offline.', 'Buy on the official site, then save the code or PDF here: it stays in Documents, even offline.', 'Achetez sur le site officiel, puis enregistrez ici le code ou le PDF : il reste dans Documents, même hors ligne.', 'Compra en la web oficial y guarda aquí el código o el PDF: lo tendrás en Documentos, incluso sin conexión.', 'Kup na oficjalnej stronie, a potem zapisz tu kod lub PDF: zostanie w Dokumentach, także offline.', 'Cumpără de pe site-ul oficial, apoi salvează aici codul sau PDF-ul: rămâne în Documente, chiar și offline.'],
  tapGo: ['Bus, tram e metro: puoi pagare anche con la carta contactless ai tornelli e sui bus.', 'Bus, tram and metro: you can also pay with a contactless card at gates and on board.', 'Bus, tram et métro : paiement aussi par carte sans contact aux portiques et à bord.', 'Bus, tranvía y metro: también puedes pagar con tarjeta contactless en tornos y a bordo.', 'Autobus, tramwaj i metro: możesz płacić kartą zbliżeniową na bramkach i w pojeździe.', 'Autobuz, tramvai și metrou: poți plăti și cu card contactless la turnichete și la bord.'],
  ticketName: ['Nome del biglietto', 'Ticket name', 'Nom du billet', 'Nombre del billete', 'Nazwa biletu', 'Numele biletului'],
  numbers: ['Numeri utili', 'Useful numbers', 'Numéros utiles', 'Números útiles', 'Przydatne numery', 'Numere utile'],
  n112: ['Emergenza (tutto)', 'Emergency (all)', 'Urgence (tout)', 'Emergencia (todo)', 'Alarmowy (wszystko)', 'Urgență (toate)'],
  n113: ['Polizia di Stato', 'State Police', "Police d'État", 'Policía del Estado', 'Policja Państwowa', 'Poliția de Stat'],
  n118: ['Ambulanza', 'Ambulance', 'Ambulance', 'Ambulancia', 'Karetka', 'Ambulanță'],
  n115: ['Vigili del fuoco', 'Fire brigade', 'Pompiers', 'Bomberos', 'Straż pożarna', 'Pompieri'],
  nTaxi: ['Radiotaxi Roma', 'Rome radio taxi', 'Radio taxi Rome', 'Radiotaxi Roma', 'Radio taxi Rzym', 'Radiotaxi Roma'],
  nearYou: ['Vicino a te', 'Near you', 'Près de vous', 'Cerca de ti', 'W pobliżu', 'Aproape de tine'],
  shareMsg: ['Ho bisogno di aiuto. La mia posizione:', 'I need help. My location:', "J'ai besoin d'aide. Ma position :", 'Necesito ayuda. Mi ubicación:', 'Potrzebuję pomocy. Moja lokalizacja:', 'Am nevoie de ajutor. Locația mea:'],
  sharedUntil: ['Condivisa fino alle {t}', 'Shared until {t}', "Partagée jusqu'à {t}", 'Compartida hasta las {t}', 'Udostępniona do {t}', 'Partajată până la {t}'],
  shareNow: ['Invia la posizione a un contatto', 'Send location to a contact', 'Envoyer la position à un contact', 'Enviar ubicación a un contacto', 'Wyślij lokalizację kontaktowi', 'Trimite locația unui contact'],
  listenIt: ['Ascolta in italiano', 'Listen in Italian', 'Écouter en italien', 'Escuchar en italiano', 'Posłuchaj po włosku', 'Ascultă în italiană'],
  embassyOf: ['Ambasciata', 'Embassy', 'Ambassade', 'Embajada', 'Ambasada', 'Ambasada'],
  verifyNote: ['Dati da verificare sul sito ufficiale.', 'Check details on the official site.', 'À vérifier sur le site officiel.', 'Verifica los datos en la web oficial.', 'Sprawdź dane na oficjalnej stronie.', 'Verifică datele pe site-ul oficial.'],
  meetName: ['Nome del punto', 'Place name', 'Nom du lieu', 'Nombre del lugar', 'Nazwa miejsca', 'Numele locului'],
  meetTime: ['Ora', 'Time', 'Heure', 'Hora', 'Godzina', 'Ora'],
  meetPick: ['Tocca la mappa per spostare il punto.', 'Tap the map to move the point.', 'Touchez la carte pour déplacer le point.', 'Toca el mapa para mover el punto.', 'Dotknij mapy, by przesunąć punkt.', 'Atinge harta ca să muți punctul.'],
  useMyPos: ['Usa la mia posizione', 'Use my location', 'Utiliser ma position', 'Usar mi ubicación', 'Użyj mojej lokalizacji', 'Folosește locația mea'],
  choosePlace: ['Scegli un luogo', 'Choose a place', 'Choisir un lieu', 'Elegir un lugar', 'Wybierz miejsce', 'Alege un loc'],
  sendMsg: ['Avviso ai membri', 'Alert to members', 'Alerte aux membres', 'Aviso a los miembros', 'Komunikat do uczestników', 'Mesaj către membri'],
  msgPh: ['Es. Ci vediamo alle 12:15 sotto il colonnato', 'E.g. Meet at 12:15 under the colonnade', 'Ex. Rendez-vous à 12h15 sous la colonnade', 'Ej. Nos vemos a las 12:15 bajo la columnata', 'Np. Zbiórka o 12:15 pod kolumnadą', 'Ex. Ne vedem la 12:15 sub colonadă'],
  send: ['Invia', 'Send', 'Envoyer', 'Enviar', 'Wyślij', 'Trimite'],
  msgSent: ['Avviso inviato al gruppo', 'Alert sent to the group', 'Alerte envoyée au groupe', 'Aviso enviado al grupo', 'Komunikat wysłany', 'Mesaj trimis grupului'],
  planSent: ['Programma inviato a {n} persone', 'Plan sent to {n} people', 'Programme envoyé à {n} personnes', 'Plan enviado a {n} personas', 'Plan wysłany do {n} osób', 'Program trimis la {n} persoane'],
  planPublished: ['Nuovo programma dal capogruppo', 'New plan from your leader', "Nouveau programme de l'accompagnateur", 'Nuevo plan del responsable', 'Nowy plan od lidera', 'Program nou de la lider'],
  memberOut: ['{name} è fuori zona', '{name} is out of the zone', '{name} est hors zone', '{name} está fuera de la zona', '{name} jest poza strefą', '{name} e în afara zonei'],
  memberOutD: ['È a {d} dal gruppo. Le abbiamo già mostrato la strada per tornare.', "They're {d} from the group. We've already shown them the way back.", 'À {d} du groupe. Nous lui avons déjà montré le chemin du retour.', 'Está a {d} del grupo. Ya le mostramos el camino de vuelta.', 'Jest {d} od grupy. Pokazaliśmy już drogę powrotną.', 'E la {d} de grup. I-am arătat deja drumul înapoi.'],
  memberOk: ['{name} dice di stare bene', '{name} says they are fine', '{name} dit aller bien', '{name} dice que está bien', '{name} mówi, że wszystko w porządku', '{name} spune că e bine'],
  memberSos: ['{name} ha chiesto aiuto (SOS)', '{name} asked for help (SOS)', "{name} a demandé de l'aide (SOS)", '{name} ha pedido ayuda (SOS)', '{name} prosi o pomoc (SOS)', '{name} a cerut ajutor (SOS)'],
  zoneDx: ['Il gruppo è a questa distanza:', 'The group is this far away:', 'Le groupe est à cette distance :', 'El grupo está a esta distancia:', 'Grupa jest w tej odległości:', 'Grupul e la această distanță:'],
  callLeader: ['Chiama il capogruppo', 'Call your leader', "Appeler l'accompagnateur", 'Llamar al responsable', 'Zadzwoń do lidera', 'Sună liderul'],
  leaderPhone: ['Telefono (per le chiamate dal gruppo)', 'Phone (for calls from the group)', 'Téléphone (pour les appels du groupe)', 'Teléfono (para llamadas del grupo)', 'Telefon (do połączeń z grupy)', 'Telefon (pentru apeluri din grup)'],
  customStop: ['Tappa sulla mappa', 'Stop on the map', 'Étape sur la carte', 'Parada en el mapa', 'Przystanek na mapie', 'Oprire pe hartă'],
  moveUp: ['Su', 'Up', 'Monter', 'Subir', 'W górę', 'Sus'],
  hotel: ['Il tuo hotel', 'Your hotel', 'Votre hôtel', 'Tu hotel', 'Twój hotel', 'Hotelul tău'],
  hotelName: ['Nome hotel', 'Hotel name', "Nom de l'hôtel", 'Nombre del hotel', 'Nazwa hotelu', 'Numele hotelului'],
  hotelAddress: ['Indirizzo', 'Address', 'Adresse', 'Dirección', 'Adres', 'Adresă'],
  hotelFind: ['Trova sulla mappa', 'Find on map', 'Trouver sur la carte', 'Buscar en el mapa', 'Znajdź na mapie', 'Găsește pe hartă'],
  hotelNotFound: ['Indirizzo non trovato', 'Address not found', 'Adresse introuvable', 'Dirección no encontrada', 'Nie znaleziono adresu', 'Adresă negăsită'],
  language: ['Lingua', 'Language', 'Langue', 'Idioma', 'Język', 'Limbă'],
  role: ['Ruolo', 'Role', 'Rôle', 'Rol', 'Rola', 'Rol'],
  changeRole: ['Cambia ruolo o gruppo', 'Change role or group', 'Changer de rôle ou de groupe', 'Cambiar rol o grupo', 'Zmień rolę lub grupę', 'Schimbă rolul sau grupul'],
  leaveGroup: ['Esci dal gruppo', 'Leave group', 'Quitter le groupe', 'Salir del grupo', 'Opuść grupę', 'Ieși din grup'],
  resetApp: ['Cancella tutto da questo telefono', 'Erase everything from this phone', 'Tout effacer de ce téléphone', 'Borrar todo de este teléfono', 'Usuń wszystko z tego telefonu', 'Șterge tot de pe acest telefon'],
  resetConfirm: ['Cancellare documenti, programma e impostazioni da questo telefono?', 'Erase documents, plan and settings from this phone?', 'Effacer documents, programme et réglages de ce téléphone ?', '¿Borrar documentos, plan y ajustes de este teléfono?', 'Usunąć dokumenty, plan i ustawienia z tego telefonu?', 'Ștergi documentele, programul și setările de pe acest telefon?'],
  syncOn: ['Sincronizzato con il gruppo', 'Synced with the group', 'Synchronisé avec le groupe', 'Sincronizado con el grupo', 'Zsynchronizowane z grupą', 'Sincronizat cu grupul'],
  offlineNow: ['Sei offline: documenti, programma e frasi restano disponibili.', "You're offline: documents, plan and phrases are still available.", 'Hors ligne : documents, programme et phrases restent disponibles.', 'Sin conexión: documentos, plan y frases siguen disponibles.', 'Jesteś offline: dokumenty, plan i zwroty są dostępne.', 'Ești offline: documentele, programul și frazele rămân disponibile.'],
  installApp: ["Installa l'app", 'Install the app', "Installer l'app", 'Instalar la app', 'Zainstaluj aplikację', 'Instalează aplicația'],
  members: ['Membri', 'Members', 'Membres', 'Miembros', 'Uczestnicy', 'Membri'],
  inZone: ['nella zona', 'in the zone', 'dans la zone', 'en la zona', 'w strefie', 'în zonă'],
  lastSeen: ['visto {t}', 'seen {t}', 'vu {t}', 'visto {t}', 'widziany {t}', 'văzut {t}'],
  noPosition: ['senza posizione', 'no location', 'sans position', 'sin ubicación', 'brak lokalizacji', 'fără locație'],
  tempNow: ['{n}°', '{n}°', '{n}°', '{n}°', '{n}°', '{n}°'],
  gotIt: ['Ho capito', 'Got it', "J'ai compris", 'Entendido', 'Rozumiem', 'Am înțeles'],
  routeTo: ['Strada per {place}', 'Route to {place}', 'Itinéraire vers {place}', 'Ruta a {place}', 'Trasa do {place}', 'Traseu spre {place}'],
  closedNow: ['Chiuso dalle {t}', 'Closed since {t}', 'Fermé depuis {t}', 'Cerrado desde las {t}', 'Zamknięte od {t}', 'Închis de la {t}'],
  // sostituisce il testo del design: ora l'orario si sceglie dall'orologio
  edHint: ["Tocca l'orario per cambiarlo, il mezzo per cambiarlo, ↑ per spostare la tappa.", 'Tap a time to change it, the transport to switch it, ↑ to move a stop.', "Touchez l'heure pour la changer, le transport pour le modifier, ↑ pour déplacer l'étape.", 'Toca la hora para cambiarla, el transporte para cambiarlo, ↑ para mover la parada.', 'Dotknij godziny, by ją zmienić, środka transportu, by go zmienić, ↑, by przesunąć przystanek.', 'Atinge ora ca s-o schimbi, transportul ca să-l schimbi, ↑ ca să muți oprirea.'],
  theftHere: ['Qui i furti sono frequenti, soprattutto nella folla e sui mezzi.', 'Thefts are common here, especially in crowds and on transport.', 'Les vols sont fréquents ici, surtout dans la foule et les transports.', 'Aquí los robos son frecuentes, sobre todo entre la multitud y en el transporte.', 'Kradzieże są tu częste, zwłaszcza w tłumie i w komunikacji.', 'Aici furturile sunt frecvente, mai ales în aglomerație și în mijloacele de transport.'],
  memberPhone: ['Telefono (lo vede solo il tuo gruppo)', 'Phone (only your group sees it)', 'Téléphone (visible seulement par votre groupe)', 'Teléfono (solo lo ve tu grupo)', 'Telefon (widzi go tylko twoja grupa)', 'Telefon (îl vede doar grupul tău)'],
  callName: ['Chiama {name}', 'Call {name}', 'Appeler {name}', 'Llamar a {name}', 'Zadzwoń: {name}', 'Sună-l pe {name}'],
  membersNow: ['Dove sono i membri', 'Where members are', 'Où sont les membres', 'Dónde están los miembros', 'Gdzie są uczestnicy', 'Unde sunt membrii'],
  haveAccount: ['Ho già un account', 'I already have an account', "J'ai déjà un compte", 'Ya tengo una cuenta', 'Mam już konto', 'Am deja un cont'],
  account: ['Account', 'Account', 'Compte', 'Cuenta', 'Konto', 'Cont'],
  accountD: ['Collega la tua email per ritrovare documenti e gruppo se cambi o perdi il telefono.', 'Link your email to recover documents and group if you change or lose your phone.', 'Associez votre email pour retrouver documents et groupe si vous changez ou perdez de téléphone.', 'Vincula tu email para recuperar documentos y grupo si cambias o pierdes el teléfono.', 'Połącz e-mail, by odzyskać dokumenty i grupę po zmianie lub utracie telefonu.', 'Leagă emailul ca să-ți recuperezi documentele și grupul dacă schimbi sau pierzi telefonul.'],
  email: ['Email', 'Email', 'E-mail', 'Correo electrónico', 'E-mail', 'Email'],
  linkEmail: ['Collega email', 'Link email', "Associer l'email", 'Vincular email', 'Połącz e-mail', 'Leagă emailul'],
  checkMail: ['Controlla la posta e conferma il link.', 'Check your inbox and confirm the link.', 'Vérifiez vos mails et confirmez le lien.', 'Revisa tu correo y confirma el enlace.', 'Sprawdź pocztę i potwierdź link.', 'Verifică emailul și confirmă linkul.'],
  linkedAs: ['Collegato a {email}', 'Linked to {email}', 'Associé à {email}', 'Vinculado a {email}', 'Połączono z {email}', 'Legat de {email}'],
  loginTitle: ['Bentornato', 'Welcome back', 'Bon retour', 'Bienvenido de nuevo', 'Witaj ponownie', 'Bine ai revenit'],
  loginD: ["Inserisci l'email collegata: ti mandiamo un codice di 6 cifre.", "Enter your linked email: we'll send you a 6-digit code.", "Saisissez l'email associé : nous vous envoyons un code à 6 chiffres.", 'Escribe el email vinculado: te enviaremos un código de 6 cifras.', 'Wpisz połączony e-mail: wyślemy 6-cyfrowy kod.', 'Introdu emailul legat: îți trimitem un cod de 6 cifre.'],
  sendCode: ['Invia il codice', 'Send code', 'Envoyer le code', 'Enviar código', 'Wyślij kod', 'Trimite codul'],
  code: ['Codice ricevuto', 'Code received', 'Code reçu', 'Código recibido', 'Otrzymany kod', 'Codul primit'],
  codeWrong: ['Codice non valido o scaduto', 'Invalid or expired code', 'Code invalide ou expiré', 'Código no válido o caducado', 'Kod nieprawidłowy lub wygasł', 'Cod invalid sau expirat'],
  restoreTitle: ['Ripristina i documenti', 'Restore your documents', 'Restaurer vos documents', 'Restaurar tus documentos', 'Przywróć dokumenty', 'Restaurează documentele'],
  restoreD: ['Abbiamo trovato {n} documenti cifrati del tuo account. Inserisci il PIN che usavi sull\'altro telefono.', 'We found {n} encrypted documents in your account. Enter the PIN you used on your other phone.', 'Nous avons trouvé {n} documents chiffrés. Saisissez le code utilisé sur votre autre téléphone.', 'Encontramos {n} documentos cifrados en tu cuenta. Introduce el PIN que usabas en el otro teléfono.', 'Znaleźliśmy {n} zaszyfrowanych dokumentów. Wpisz PIN z poprzedniego telefonu.', 'Am găsit {n} documente criptate în contul tău. Introdu PIN-ul folosit pe celălalt telefon.'],
  startFresh: ['Ricomincia con un nuovo PIN', 'Start over with a new PIN', 'Recommencer avec un nouveau code', 'Empezar con un PIN nuevo', 'Zacznij od nowa z nowym PIN-em', 'Începe cu un PIN nou'],
  dayOfN: ['Giorno {n} di {m}', 'Day {n} of {m}', 'Jour {n} sur {m}', 'Día {n} de {m}', 'Dzień {n} z {m}', 'Ziua {n} din {m}'],
  dayN: ['Giorno {n}', 'Day {n}', 'Jour {n}', 'Día {n}', 'Dzień {n}', 'Ziua {n}'],
  planOf: ['Programma di {date}', 'Plan for {date}', 'Programme du {date}', 'Plan del {date}', 'Plan na {date}', 'Programul din {date}'],
  tripDates: ['Date del viaggio', 'Trip dates', 'Dates du voyage', 'Fechas del viaje', 'Daty podróży', 'Datele călătoriei'],
  tripFrom: ['Arrivo', 'Arrival', 'Arrivée', 'Llegada', 'Przyjazd', 'Sosire'],
  tripTo: ['Partenza', 'Departure', 'Départ', 'Salida', 'Wyjazd', 'Plecare'],
  bioTitle: ['Sblocco con impronta o Face ID', 'Unlock with fingerprint or Face ID', 'Déverrouiller par empreinte ou Face ID', 'Desbloquear con huella o Face ID', 'Odblokuj odciskiem lub Face ID', 'Deblocare cu amprenta sau Face ID'],
  bioD: ['Inserisci il PIN per attivarlo. Il PIN resta valido come riserva.', 'Enter your PIN to turn it on. Your PIN still works as a backup.', 'Saisissez votre code pour l’activer. Le code reste valable en secours.', 'Introduce el PIN para activarlo. El PIN sigue sirviendo de reserva.', 'Wpisz PIN, by włączyć. PIN nadal działa awaryjnie.', 'Introdu PIN-ul ca să-l activezi. PIN-ul rămâne valabil ca rezervă.'],
  bioOn: ['Sblocco biometrico attivo', 'Biometric unlock on', 'Déverrouillage biométrique activé', 'Desbloqueo biométrico activado', 'Odblokowanie biometryczne włączone', 'Deblocare biometrică activă'],
  bioUnsupported: ['Questo telefono non lo supporta: usa il PIN.', "This phone doesn't support it: use your PIN.", 'Ce téléphone ne le permet pas : utilisez le code.', 'Este teléfono no lo admite: usa el PIN.', 'Ten telefon tego nie obsługuje: użyj PIN-u.', 'Telefonul nu suportă: folosește PIN-ul.'],
  pushTitle: ['Avvisi anche ad app chiusa', 'Alerts even when the app is closed', "Alertes même app fermée", 'Avisos con la app cerrada', 'Powiadomienia przy zamkniętej aplikacji', 'Alerte și cu aplicația închisă'],
  pushD: ['Fuori zona, SOS, messaggi e nuovo programma del gruppo.', 'Out of zone, SOS, messages and new group plan.', 'Hors zone, SOS, messages et nouveau programme.', 'Fuera de zona, SOS, mensajes y nuevo plan del grupo.', 'Poza strefą, SOS, wiadomości i nowy plan grupy.', 'În afara zonei, SOS, mesaje și program nou.'],
  pushDenied: ['Notifiche non consentite: attivale nelle impostazioni del telefono.', 'Notifications blocked: allow them in your phone settings.', 'Notifications bloquées : autorisez-les dans les réglages.', 'Notificaciones bloqueadas: actívalas en los ajustes del teléfono.', 'Powiadomienia zablokowane: włącz je w ustawieniach telefonu.', 'Notificări blocate: permite-le din setările telefonului.'],
  unlock: ['Sblocca con impronta / Face ID', 'Unlock with fingerprint / Face ID', 'Déverrouiller (empreinte / Face ID)', 'Desbloquear con huella / Face ID', 'Odblokuj odciskiem / Face ID', 'Deblochează cu amprenta / Face ID'],
  roleAgency: ['Agenzia', 'Agency', 'Agence', 'Agencia', 'Biuro podróży', 'Agenție'],
  roleAgencyD: ['Crea i codici per i tuoi capigruppo e vedi chi li usa.', 'Create codes for your group leaders and see who uses them.', 'Créez les codes de vos accompagnateurs et suivez leur usage.', 'Crea códigos para tus responsables y mira quién los usa.', 'Twórz kody dla liderów grup i sprawdzaj, kto ich używa.', 'Creează coduri pentru liderii tăi și vezi cine le folosește.'],
  licCode: ['Codice di attivazione', 'Activation code', "Code d'activation", 'Código de activación', 'Kod aktywacyjny', 'Cod de activare'],
  groupLicCode: ['Codice del pacchetto gruppo', 'Group package code', 'Code du forfait groupe', 'Código del paquete de grupo', 'Kod pakietu grupowego', 'Codul pachetului de grup'],
  agencyLicCode: ['Codice agenzia', 'Agency code', 'Code agence', 'Código de agencia', 'Kod biura', 'Codul agenției'],
  licCodeD: ["Lo ricevi con l'acquisto. I giorni partono dalla prima attivazione.", 'You get it when you buy. Days start from the first activation.', "Vous le recevez à l'achat. Les jours comptent dès la première activation.", 'Lo recibes al comprar. Los días cuentan desde la primera activación.', 'Otrzymasz go przy zakupie. Dni liczą się od pierwszej aktywacji.', 'Îl primești la cumpărare. Zilele încep de la prima activare.'],
  licNotFound: ['Codice non valido', 'Invalid code', 'Code non valide', 'Código no válido', 'Nieprawidłowy kod', 'Cod invalid'],
  licUsed: ["Codice già usato da un'altra persona", 'Code already used by someone else', 'Code déjà utilisé par une autre personne', 'Código ya usado por otra persona', 'Kod został już użyty przez inną osobę', 'Cod deja folosit de altcineva'],
  licExpired: ['Codice scaduto', 'Code expired', 'Code expiré', 'Código caducado', 'Kod wygasł', 'Cod expirat'],
  licWrongKind: ['Questo codice è per un altro tipo di pacchetto', 'This code is for a different package', 'Ce code correspond à un autre forfait', 'Este código es de otro tipo de paquete', 'Ten kod dotyczy innego pakietu', 'Acest cod este pentru alt tip de pachet'],
  groupFull: ['Il gruppo è al completo', 'The group is full', 'Le groupe est complet', 'El grupo está completo', 'Grupa jest pełna', 'Grupul este complet'],
  noSlots: ['Hai usato tutti i gruppi del pacchetto', "You've used all the groups in your package", 'Vous avez utilisé tous les groupes du forfait', 'Has usado todos los grupos del paquete', 'Wykorzystano wszystkie grupy z pakietu', 'Ai folosit toate grupurile din pachet'],
  seatsLeft: ['{n} posti liberi', '{n} places left', '{n} places libres', '{n} plazas libres', 'Wolne miejsca: {n}', '{n} locuri libere'],
  accessUntil: ['Accesso fino al {date}', 'Access until {date}', "Accès jusqu'au {date}", 'Acceso hasta el {date}', 'Dostęp do {date}', 'Acces până la {date}'],
  daysLeft: ['ancora {n} giorni', '{n} days left', 'encore {n} jours', 'quedan {n} días', 'zostało dni: {n}', 'încă {n} zile'],
  lastDay: ['ultimo giorno', 'last day', 'dernier jour', 'último día', 'ostatni dzień', 'ultima zi'],
  expiredTitle: ['Accesso scaduto', 'Access expired', 'Accès expiré', 'Acceso caducado', 'Dostęp wygasł', 'Acces expirat'],
  expiredD: ['Il pacchetto è finito. Documenti e SOS restano sempre disponibili.', 'Your package has ended. Documents and SOS stay available.', 'Le forfait est terminé. Documents et SOS restent disponibles.', 'El paquete ha terminado. Documentos y SOS siguen disponibles.', 'Pakiet się skończył. Dokumenty i SOS pozostają dostępne.', 'Pachetul s-a încheiat. Documentele și SOS rămân disponibile.'],
  expiredMember: ['Chiedi al capogruppo di rinnovare il pacchetto del gruppo.', 'Ask your group leader to renew the group package.', "Demandez à l'accompagnateur de renouveler le forfait.", 'Pide al responsable que renueve el paquete del grupo.', 'Poproś lidera o odnowienie pakietu grupy.', 'Roagă liderul să reînnoiască pachetul grupului.'],
  renew: ['Rinnova', 'Renew', 'Renouveler', 'Renovar', 'Odnów', 'Reînnoiește'],
  renewed: ['Pacchetto rinnovato', 'Package renewed', 'Forfait renouvelé', 'Paquete renovado', 'Pakiet odnowiony', 'Pachet reînnoit'],
  newCode: ['Nuovo codice', 'New code', 'Nouveau code', 'Código nuevo', 'Nowy kod', 'Cod nou'],
  agencyTitle: ['La tua agenzia', 'Your agency', 'Votre agence', 'Tu agencia', 'Twoje biuro', 'Agenția ta'],
  agencyPkg: ['Gruppi usati {n} di {m} · pacchetto valido fino al {date}', 'Groups used {n} of {m} · package valid until {date}', "Groupes utilisés {n} sur {m} · forfait valable jusqu'au {date}", 'Grupos usados {n} de {m} · paquete válido hasta el {date}', 'Wykorzystane grupy: {n} z {m} · pakiet ważny do {date}', 'Grupuri folosite {n} din {m} · pachet valabil până la {date}'],
  agencyPeople: ['Fino a {n} persone per gruppo · {d} giorni da quando il capogruppo attiva il codice', 'Up to {n} people per group · {d} days from when the leader activates the code', "Jusqu'à {n} personnes par groupe · {d} jours dès l'activation", 'Hasta {n} personas por grupo · {d} días desde la activación', 'Do {n} osób w grupie · {d} dni od aktywacji kodu', 'Până la {n} persoane pe grup · {d} zile de la activare'],
  issueCode: ['Crea un codice per un capogruppo', 'Create a code for a group leader', 'Créer un code pour un accompagnateur', 'Crear un código para un responsable', 'Utwórz kod dla lidera grupy', 'Creează un cod pentru un lider'],
  issueNote: ['Viaggio o capogruppo (es. Gita Firenze · Marco)', 'Trip or leader (e.g. Florence trip · Marco)', 'Voyage ou accompagnateur (ex. Florence · Marco)', 'Viaje o responsable (ej. Florencia · Marco)', 'Wycieczka lub lider (np. Florencja · Marco)', 'Excursie sau lider (ex. Florența · Marco)'],
  codeReady: ['Codice pronto: dallo al capogruppo', 'Code ready: give it to the group leader', "Code prêt : donnez-le à l'accompagnateur", 'Código listo: dáselo al responsable', 'Kod gotowy: przekaż go liderowi', 'Cod gata: dă-l liderului'],
  copy: ['Copia', 'Copy', 'Copier', 'Copiar', 'Kopiuj', 'Copiază'],
  copied: ['Copiato', 'Copied', 'Copié', 'Copiado', 'Skopiowano', 'Copiat'],
  shareCodeMsg: ["Il tuo codice Custode per il gruppo: {code}. Apri l'app, scegli Capogruppo e inseriscilo.", 'Your Custode group code: {code}. Open the app, choose Group leader and enter it.', "Votre code Custode pour le groupe : {code}. Ouvrez l'app, choisissez Accompagnateur et saisissez-le.", 'Tu código Custode para el grupo: {code}. Abre la app, elige Responsable e introdúcelo.', 'Twój kod Custode dla grupy: {code}. Otwórz aplikację, wybierz Lider grupy i wpisz go.', 'Codul tău Custode pentru grup: {code}. Deschide aplicația, alege Lider și introdu-l.'],
  statusUnused: ['Da usare', 'Not used yet', 'Pas encore utilisé', 'Sin usar', 'Nieużyty', 'Nefolosit'],
  statusActive: ['Attivo fino al {date}', 'Active until {date}', "Actif jusqu'au {date}", 'Activo hasta el {date}', 'Aktywny do {date}', 'Activ până la {date}'],
  statusExpired: ['Scaduto', 'Expired', 'Expiré', 'Caducado', 'Wygasł', 'Expirat'],
  peopleOf: ['{n}/{m} persone', '{n}/{m} people', '{n}/{m} personnes', '{n}/{m} personas', '{n}/{m} osób', '{n}/{m} persoane'],
  agencyEmpty: ['Nessun codice ancora: crea il primo per un tuo capogruppo.', 'No codes yet: create the first one for a group leader.', "Aucun code : créez le premier pour un accompagnateur.", 'Aún no hay códigos: crea el primero para un responsable.', 'Brak kodów: utwórz pierwszy dla lidera grupy.', 'Niciun cod încă: creează primul pentru un lider.'],
  noAccessYet: ['Nessun pacchetto attivo', 'No active package', 'Aucun forfait actif', 'Ningún paquete activo', 'Brak aktywnego pakietu', 'Niciun pachet activ'],
  rolesSolo: ['Turista singolo', 'Solo traveller', 'Voyageur seul', 'Viajero solo', 'Turysta indywidualny', 'Turist singur'],
};
